# 루트 Exception을 정의해서 API로부터 호출자를 보호하자

파이썬은 언어와 표준 라이브러리용 내장 예외 계층을 갖추고 있어 오류를 보고할 때 내장 예외 타입을 사용할 가능성이 크다. <br>
예를 들어 함수에 올바르지 않은 인수가 넘어오면 ValueError 예외를 일으킬 수 있다.
```py
def determine_weight(volume, density):
    if density <= 0:
        raise ValueError('Density must be positive')
```

몇몇 경우는 내장 예외 타입을 사용할 수 있겠지만, API용으로는 자신만의 예외 계층을 정의하는 방법이 더 강력하다 <br>
예외 계층은 모듈 내에서 루트 Exception을 제공하고 해당 모듈에서 일어나는 다른 예외가 루트 예외를 상속받도록 해야 한다.
```py
class Error(Exception):
    """
    이 모듈의 예외를 위한 기본 클래스
    """

class InvalidDensityError(Error):
    """
    인수로 넘어온 Density 값에 문제가 있음.
    """
```

모듈에 루트 예외 두고 API 사용자는 루트 예외를 잡아내는 try/except문으로 함수를 호출하여 예외가 너무 멀리 퍼져나가는 것을 방지할 수 있다.
```py
# 예외가 퍼져나가는 것을 방지
try:
    weight = determine_weight(1, -1)
except Error as e:
    # 해당 예외를 처리
    print(e)
```

이런 보호는 세 가지 측면에서 유용하다.

1. 루트 예외가 있으면 호출자가 API를 사용할 때 발생한 문제점을 이해할 수 있다.
2. API 모듈의 코드에 있는 버그를 찾는 데 도움이 된다. (=> 모듈 내부에 정의한 예외만 의도적으로 일으키기 때문에 찾기 쉽다.)
3. API의 미래를 대비할 수 있다. 시간이 지나 특정 상황에 더 구체적인 예외를 제공하려고 할 때 쉽게 확장할 수 있다.\

## 정리
1. 작성 중인 모듈에 모듈만의 루트 예외를 정의하면 API로부터 API 사용자를 보호할 수 있다.
2. 루트 예외를 잡으면 API를 사용하는 코드에 숨은 버그를 찾는 데 도움이 될 수 있다.
3. 파이썬 Exception 기반 클래스(=즉 의도하지 않은 예외이기 때문)를 잡으면 API 구현에 있는 버그를 찾는 데 도움이 될 수 있다.
4. 루트 예외를 이용하면 API를 사용하는 코드에 영향을 주지 않고 나중에 더 구체적인 예외로 확장하기 쉽다.